[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4.3", "Cython"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/version.py"
write_to_template = "__version__ = \"{version}\""
